export enum AppActionTypes {
  APP_INITIALIZE_REQUEST = 'app/INITIALIZE_REQUEST',
  APP_INITIALIZED_SET = 'app/INITIALIZE_SET',
  FIREBASE_INITIALIZED_SET = 'firebase/INITIALIZE_SET',
  APP_GELOCATION_SET = 'app/GELOCATION_SET',
  APP_IP_SET = 'app/IP_SET',
  APP_LOCAL_STORAGE_REHYDRATE = 'app/localstorage/REHYDRATE',
  APP_LOCAL_STORAGE_SET = 'app/localstorage/SET',
  APP_TOAST_SET = 'app/toast/SET',
  APP_SMS_APP_LINKS_REQUEST = 'app/sms/APP_LINKS_REQUEST',
  APP_LOADING_OVERLAY_SET = 'app/sms/APP_LOADING_OVERLAY_SET',
}

export enum StoreActionTypes {
  STORE_CONFIG_TYPES_SET = 'store/config/TYPES_SET',
  STORE_DETAILS_REQUEST = 'store/DETAILS_REQUEST',
  STORE_DETAILS_SET = 'store/DETAILS_SET',
  STORE_OFFERS_SET = 'store/OFFERS_SET',
  STORE_CONFIG_REQUEST = 'store/TYPE_REQUEST',
}

export enum AuthActionTypes {
  AUTH_STATE_CHANGE_SET = 'auth/STATE_CHANGE_SET',
  AUTH_ADDITIONAL_USER_INFO_SET = 'auth/ADDITIONAL_USER_INFO_SET',
  AUTH_EMAIL_SIGN_IN_REQUEST = 'auth/EMAIL_LOGIN_REQUEST',
  AUTH_SOCIAL_SIGN_IN_REQUEST = 'auth/SOCIAL_SIGN_IN_REQUEST',
  AUTH_SOCIAL_SIGN_UP_REQUEST = 'auth/SOCIAL_SIGN_UP_REQUEST',
  AUTH_PHONE_AND_ADDITIONAL_SIGN_UP_REQUEST = 'auth/AUTH_PHONE_AND_ADDITIONAL_SIGN_UP_REQUEST',
  AUTH_PHONE_SIGN_IN_OR_SIGN_UP_REQUEST = 'auth/PHONE_SIGN_IN_OR_SIGN_UP_REQUEST',
  AUTH_LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST',
  AUTH_EMAIL_PASSWORD_LOGIN_REQUEST = 'auth/EMAIL_PASSWORD_LOGIN_REQUEST',
  AUTH_CREATE_EMAIL_SIGN_UP_REQUEST = '/auth/CREATE_EMAIL_PASSWORD_USER_REQUEST',
  AUTH_PROFILE_CHANGE_LISTEN_START = 'auth/PROFILE_CHANGE_LISTEN_START',
  AUTH_PROFILE_CHANGE_LISTEN_CANCEL = 'auth/PROFILE_CHANGE_LISTEN_CANCEL',
  AUTH_STATE_CHANGE_LISTEN_START = 'auth/STATE_CHANGE_LISTEN_START',
  AUTH_STATE_CHANGE_LISTEN_CANCEL = 'auth/STATE_CHANGE_LISTEN_CANCEL',
  AUTH_PROFILE_UPDATE_REQUEST = 'auth/profile/UPDATE_REQUEST',
  AUTH_PROFILE_AND_IMAGE_UPDATE_REQUEST = 'auth/profile/UPDATE_WITH_IMAGE',
  AUTH_API_ERROR_LISTEN_START = 'auth/API_ERROR_LISTEN_START',
  AUTH_API_ERROR_LISTEN_CANCEL = 'auth/API_ERROR_LISTEN_CANCEL',
  AUTH_PHONE_CONFIRM_REQUEST = 'auth/PHONE_CONFIRM_REQUEST',
  AUTH_VERIFICATION_STATE_SET = 'auth/VERIFICATION_STATE_SET',
}

export enum ErrorActionTypes {
  ERROR_APP_INITIALIZE = 'error/app/INITIALIZE_ERROR',
  ERROR_SET = 'error/SET',
  ERROR_API_SET = 'error/API_ERROR_SET',
  ERROR_FATAL_SET = 'error/FATAL_ERROR_SET',
  ERROR_SEARCH_SET = 'error/SEARCH_ERROR_SET',
  ERROR_FIREBASE_SET = 'error/FIREBASE_ERROR_SET',
  ERROR_CLEAR = 'error/CLEAR',
  ERROR_CLEAR_ALL = 'error/CLEAR_ALL',
  ERROR_AUTH_SET = 'auth/ERROR_SET',
}

export enum MemberAccountActionTypes {
  ACCOUNT_MEMBER_BOOKINGS_REQUEST = 'account/member/BOOKINGS_REQUEST',
  ACCOUNT_MEMBER_BOOKING_DELETE_REQUEST = 'account/member/BOOKINGS_DELETE_REQUEST',
  ACCOUNT_MEMBER_BOOKINGS_CHECKOUT_REQUEST = '/account/member/BOOKINGS_CHECKOUT_REQUEST',
  ACCOUNT_MEMBER_ORDER_CHECKOUT_REQUEST = '/account/member/ORDER_CHECKOUT_REQUEST',
  ACCOUNT_MEMBER_BOOKING_SELECT = '/account/member/BOOKING_SELECT',
  ACCOUNT_MEMBER_BOOKINGS_SET = 'account/member/BOOKINGS_SET',
  ACCOUNT_MEMBER_PROFILE_CHANGE_REQUEST = 'account/member/PROFILE_CHANGE_REQUEST',
  ACCOUNT_MEMBER_BOOKINGS_ADD_REQUEST = 'account/member/BOOKINGS_ADD',
  ACCOUNT_MEMBER_CHECKOUT_ADD_REQUEST = 'account/member/CHECKOUT_ADD',
  ACCOUNT_MEMBER_TRANSACTION_HISTORY_REQUEST = 'account/member/TRANSACTION_HISTORY_REQUEST',
  ACCOUNT_MEMBER_TRANSACTION_HISTORY_SET = 'account/member/TRANSACTION_HISTORY_SET',
  ACCOUNT_MEMBER_ORDER_HISTORY_REQUEST = 'account/member/ORDER_HISTORY_REQUEST',
  ACCOUNT_MEMBER_ORDER_HISTORY_SET = 'account/member/ORDER_HISTORY_SET',
  ACCOUNT_MEMBER_BOOMCARD_DETAILS_REQUEST = 'account/member/BOOMCARD_DETAILS_REQUEST',
  ACCOUNT_MEMBER_BOOMCARD_DETAILS_SET = 'account/member/BOOMCARD_DETAILS_SET',
  ACCOUNT_MEMBER_BOOMCARD_DETAILS_UPDATE = 'account/member/BOOMCARD_DETAILS_UPDATE',
  ACCOUNT_MEMBER_FUNDS_DETAILS_REQUEST = 'account/member/FUNDS_DETAILS_REQUEST',
  ACCOUNT_MEMBER_FUNDS_DETAILS_SET = 'account/member/FUNDS_DETAILS_SET',
  ACCOUNT_MEMBER_FUNDS_ADD_REQUEST = 'account/member/FUNDS_ADD_REQUEST',
}

export enum MerchantAccountActionTypes {
  ACCOUNT_MERCHANT_BOOM_ACCOUNT_SET = 'account/merchant/BOOM_ACCOUNT_SET',
  ACCOUNT_MERCHANT_BOOM_ACCOUNT_REQUEST = 'account/merchant/BOOM_ACCOUNT_REQUEST',
  ACCOUNT_MERCHANT_TRANSACTION_HISTORY_REQUEST = 'account/merchant/TRANSACTION_HISTORY_REQUEST',
  ACCOUNT_MERCHANT_TRANSACTION_REQUEST = 'account/merchant/TRANSACTION_REQUEST_GET',
  ACCOUNT_MERCHANT_TRANSACTION_HISTORY_SET = 'account/merchant/TRANSACTION_HISTORY_SET',
  ACCOUNT_MERCHANT_TRANSACTIONS_SET = 'account/merchant/TRANSACTIONS_SET',
  ACCOUNT_MERCHANT_PRODUCT_DEL = 'account/merchant/PRODUCT_DELETE',
  ACCOUNT_MERCHANT_PRODUCT_UPDATE_REQUEST = 'account/merchant/PRODUCT_UPDATE_REQUEST',
  ACCOUNT_MERCHANT_PRODUCTS_SET = 'account/merchant/PRODUCTS_SET',
  ACCOUNT_MERCHANT_PRODUCTS_REQUEST = 'account/merchant/PRODUCTS_REQUEST',
  ACCOUNT_MERCHANT_PRODUCTS_CREATE_REQUEST = 'account/merchant/PRODUCTS_CREATE_REQUEST',
  ACCOUNT_MERCHANT_FILTERED_PRODUCTS_REQUEST = 'account/merchant/FILTERED_PRODUCTS_REQUEST',
  ACCOUNT_MERCHANT_OFFER_CREATE_REQUEST = 'account/merchant/OFFER_CREATE_REQUEST',
  ACCOUNT_MERCHANT_OFFER_DEL = 'account/merchant/OFFER_DELETE',
  ACCOUNT_MERCHANT_OFFERS_REQUEST = 'account/merchant/OFFERS_REQUEST',
  ACCOUNT_MERCHANT_OFFERS_SET = 'account/merchant/OFFERS_SET',
  ACCOUNT_MERCHANT_OFFERS_EDIT = 'account/merchant/OFFERS_EDIT',
  ACCOUNT_MERCHANT_FILTERED_OFFERS_REQUEST = 'account/merchant/FILTERED_OFFERS_REQUEST',
  ACCOUNT_MERCHANT_PRODUCT_AND_OFFER_CREATE = 'account/merchant/PRODUCT_AND_OFFER_CREATE',
  ACCOUNT_MERCHANT_STORE_REQUEST = 'account/merchant/STORE_REQUEST',
  ACCOUNT_MERCHANT_STORE_SET = 'account/merchant/STORE_SET',
  ACCOUNT_MERCHANT_STORE_UPDATE_REQUEST = 'account/merchant/UPDATE_REQUEST',
  ACCOUNT_MERCHANT_STORE_CREATE_REQUEST = 'account/merchant/STORE_CREATE_REQUEST',
  ACCOUNT_MERCHANT_IMAGE_SET = 'account/merchant/IMAGE_SET',
  ACCOUNT_MERCHANT_INVENTORY_REQUEST = 'account/merchant/INVENTORY_REQUEST',
  ACCOUNT_MERCHANT_INVENTORY_SET = 'account/merchant/INVENTORY_SET',
  ACCOUNT_MERCHANT_TAXABLE_STATES_SET = 'account/merchant/ADD_TAXABLE_STATES',
  UPDATE_DEVICE_NICKNAME_REQUEST = 'account/merchant/UPDATE_DEVICE_NICKNAME_REQUEST',
  UPDATE_DEVICE_NICKNAME_SUCCESS = 'account/merchant/UPDATE_DEVICE_NICKNAME_SUCCESS',
  ACCOUNT_MERCHANT_REQUEST_ORDER_HISTORY = 'account/merchant/INVENTORY_ORDER_HISTORY',
  ACCOUNT_MERCHANT_FILTERED_ORDER_HISTORY = 'account/merchant/FILTERED_INVENTORY_ORDER_HISTORY',
}

export enum CategoriesActionTypes {
  CATEGORIES_REQUEST = 'publicData/CATEGORIES_REQUEST',
  CATEGORIES_SET = 'publicData/CATEGORIES_SET',
}

export enum TransactionsActionTypes {
  TRANSFER_CONFIRM_REQUEST = 'transfer/CONFIRM_REQUEST',
  TRANSFER_CANCEL_REQUEST = 'transfer/CANCEL_REQUEST',
  TRANSFER_REQUEST = 'transfer/REQUEST',
  TRANSACTION_DETAILS_REQUEST = 'transaction/DETAILS_REQUEST',
  TRANSACTION_DETAILS_SET = 'transaction/DETAILS_SET',
  TRANSACTION_WITHDRAWAL_REQUEST = 'transfer/WITHDRAWAL_REQUEST',
  TRANSACTION_WITHDRAWAL_CANCEL_REQUEST = 'transfer/WITHDRAWAL_CANCEL_REQUEST',
  TRANSACTION_WITHDRAWAL_DETAILS_REQUEST = 'transfer/WITHDRAWAL_DETAILS_REQUEST',
  TRANSACTION_WITHDRAWAL_DETAILS_SET = 'transfer/WITHDRAWAL_DETAILS_SET',
}

export enum PaymentProccesorActionTypes {
  PAYMENT_PROCESSOR_TOKEN_REQUEST = 'payment-processor/TOKEN_REQUEST',
}

export enum OfferActionTypes {
  // OFFER_REQUEST_DETAILS = 'offer/DETAILS_REQUEST',
  // OFFER_DETAILS_SET = 'offer/DETAILS_SET',
  LOCALLY_OFFER_DETAILS_SET = 'offer/LOCALLY_OFFER_DETAILS_SET',
  SIGNED_OFFER_DETAILS_SET = 'offer/SIGNED_OFFER_DETAILS_SET',
  OFFER_DETAILS_AND_STORE_OFFERS_REQUEST = 'offer/DETAILS_AND_STORE_OFFERS_REQUEST',
  OFFER_DETAILS_SET = 'offer/DETAILS_SET',
  STORE_OFFERS_SET = 'offer/OFFERS_SET',
}

export enum ImageActionTypes {
  IMAGE_UPLOAD = 'image/UPLOAD_IMAGE',
  IMAGE_GET = 'image/GET_IMAGE',
  IMAGE_DELETE = 'image/DELETE_IMAGE',
}

export enum SettingsActionTypes {
  GET_PLAID_ENV_INFO = 'GET_PLAID_ENV_INFO',
  GET_PLAID_ENV_INFO_SUCCESS = 'GET_PLAID_ENV_INFO_SUCCESS',
  GET_PLAID_ENV_INFO_FAILURE = 'GET_PLAID_ENV_INFO_FAILURE',
  GET_PLAID_ACCESS_TOKEN = 'GET_PLAID_ACCESS_TOKEN',
  GET_PLAID_ACCESS_TOKEN_SUCCESS = 'GET_PLAID_ACCESS_TOKEN_SUCCESS',
  GET_PLAID_ACCESS_TOKEN_FAILURE = 'GET_PLAID_ACCESS_TOKEN_FAILURE',
  GET_PLAID_PUBLIC_TOKEN = 'GET_PLAID_PUBLIC_TOKEN',
  GET_PLAID_PUBLIC_TOKEN_SUCCESS = 'GET_PLAID_PUBLIC_TOKEN_SUCCESS',
  GET_PLAID_PUBLIC_TOKEN_FAILURE = 'GET_PLAID_PUBLIC_TOKEN_FAILURE',
  UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS',
  REMOVE_PUBLIC_TOKEN = 'REMOVE_PUBLIC_TOKEN',
  REMOVE_BANK_ACCOUNT = 'REMOVE_BANK_ACCOUNT',
  REMOVE_BANK_ACCOUNT_SUCCESS = 'REMOVE_BANK_ACCOUNT_SUCCESS',
  REMOVE_BANK_ACCOUNT_FAILURE = 'REMOVE_BANK_ACCOUNT_FAILURE',
}

export enum FundsActionTypes {
  ADD_FUNDS_REQUEST = 'funds/ADD_REQUEST',
  TRANSFER_FUNDS_REQUEST = 'funds/TRANSFER_REQUEST',
  ADD_FUNDS_SUCCESS = 'funds/ADD_SUCCESS',
  ADD_FUNDS_FAILURE = 'funds/ADD_FAILURE',
}

export enum ProductActionTypes {
  GET_ALL_PRODUCT_REQUEST = 'product/ALL_PRODUCT_REQUEST',
  PRODUCT_DETAILS_AND_STORE_OFFERS_REQUEST = 'product/DETAILS_AND_STORE_OFFERS_REQUEST',
  PRODUCT_DETAILS_SET = 'product/DETAILS_SET',
  SET_ALL_PRODUCT_REQUEST = 'product/SET_ALL_PRODUCTS',
}

export enum TaxActionTypes {
  ACCOUNT_MEMBER_TAX_SET = 'account/member/TAX_SET',
}

export enum InventoryActionTypes {
  GET_INVENTORY_ITEM_TYPES = 'inventory/GET_INVENTORY_ITEM_TYPES',
  SET_INVENTORY_ITEM_TYPES = 'inventory/SET_INVENTORY_ITEM_TYPES',
}

export enum OrderActionTypes {
  GET_INVENTORY_ORDERS = 'order/GET_INVENTORY_ORDERS',
  SET_INVENTORY_ORDERS = 'order/SET_INVENTORY_ORDERS',
  REQUEST_INVENTORY_ORDERS = 'order/REQUEST_INVENTORY_ORDERS',
  REQUEST_INVENTORY_ORDER_CANCEL = 'order/REQUEST_INVENTORY_ORDER_CANCEL',
}

export enum ShippingActionTypes {
  SHIPPING_BOXES_SET = 'shipping/SHIPPING_BOXES_SET',
  SHIPPING_BOXES_REQUEST = 'shipping/SHIPPING_BOXES_REQUEST',
  SHIPPING_BOX_DETAILS_SET = 'shipping/SHIPPING_BOX_DETAILS_SET',
  SHIPPING_POLICIES_SET = 'shipping/SHIPPING_POLICIES_SET',
  SHIPPING_POLICIES_REQUEST = 'shipping/SHIPPING_POLICIES_REQUEST',
  SHIPPING_POLICY_DETAILS_SET = 'shipping/SHIPPING_POLICY_DETAILS_SET',
}
